version: "3"

includes:
  docker:
    dir: ./.docker
    taskfile: ./.docker
  vue:
    dir: ./vue
    taskfile: ./vue

tasks:
  env:setup:
    desc: "Setup the environment"
    cmds:
      - cp .env.example .env
    status:
      - test -f .env

  setup:
    desc: "Setup the project"
    cmds:
      - task: docker:setup
      - task: env:setup
      - task: mod:tidy
      - task: vue:setup

  dev:
    desc: "Start the development environment"
    deps: ["mod:tidy"]
    cmds:
      - air -c ./.air.toml

  dev:combined:
    desc: "Start the development environment"
    deps:
      - vue:dev
      - dev

  mod:get:
    desc: "Add dependencies"
    cmds:
      - go get {{.CLI_ARGS}}

  mod:tidy:
    desc: "Tidy dependencies"
    cmds:
      - go mod tidy
