name: gh-tracker

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
