version: "3"

tasks:
  setup:
    desc: "Setup the project"
    cmds:
      - task: env:setup
      - task: up

  env:setup:
    desc: "Setup the environment"
    cmds:
      - cp .env.example .env
    status:
      - test -f .env

  up:
    desc: "Start the docker containers"
    cmds:
      - docker compose up -d
      - task: db:port:update
  down:
    desc: "Stop the docker containers"
    cmds:
      - docker compose down {{.CLI_ARGS}} -v --remove-orphans

  rebuild:
    desc: "Rebuild the docker containers"
    cmds:
      - docker compose up -d --build
      - task: db:port:update

  recreate:
    desc: "Recreate the docker containers"
    cmds:
      - task: down
      - task: up

  logs:
    desc: "View docker container logs"
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  ps:
    desc: "List running docker containers"
    cmds:
      - docker compose ps

  db:port:show:
    desc: "Get the database port"
    cmds:
      - "docker compose port db 5432 | cut -d: -f2 | xargs echo 'Database running on port:'"

  db:port:update:
    desc: "Get the database port"
    cmds:
      - ./scripts/set_db_port.sh
