version: "3"

tasks:
  setup:
    desc: "Setup the project"
    cmds:
      - task: env:setup
      - task: deps:install

  env:setup:
    desc: "Setup the environment"
    cmds:
      - cp .env.example .env
    status:
      - test -f .env

  deps:install:
    desc: "Install dependencies"
    cmds:
      - pnpm install

  deps:add:
    desc: "Add dependencies"
    cmds:
      - pnpm add {{.CLI_ARGS}}

  deps:remove:
    desc: "Remove dependencies"
    cmds:
      - pnpm remove {{.CLI_ARGS}}

  dev:
    desc: "Start the development environment"
    deps: ["deps:install"]
    cmds:
      - pnpm build -w

  build:
    desc: "Build the project"
    deps: ["deps:install"]
    cmds:
      - pnpm build

  lint:
    desc: "Lint the project"
    deps: ["deps:install"]
    cmds:
      - pnpm eslint
      - pnpm prettier

  lint:fix:
    desc: "Fix linting issues"
    deps: ["deps:install"]
    cmds:
      - pnpm eslint:fix
      - pnpm prettier:fix
