name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.39.2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.2
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: build vue app
        run: task vue:build
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
